"""add visiblity to items table

Revision ID: 2060a4435c91
Revises: 016b77964d94
Create Date: 2025-12-08 11:23:00.800747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2060a4435c91'
down_revision: Union[str, Sequence[str], None] = '016b77964d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('found_items', sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE found_items SET visibility = 'public' WHERE visibility IS NULL")
    op.alter_column('found_items', 'visibility', nullable=False)

    op.add_column('lost_items', sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE lost_items SET visibility = 'public' WHERE visibility IS NULL")
    op.alter_column('lost_items', 'visibility', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lost_items', 'visibility')
    op.drop_column('found_items', 'visibility')
    # ### end Alembic commands ###
