"""remove reporter id from Item

Revision ID: 29ec02763e87
Revises: 9db3aead1f23
Create Date: 2025-12-16 19:25:41.181535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '29ec02763e87'
down_revision: Union[str, Sequence[str], None] = '9db3aead1f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'reporter_public_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('reporter_public_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
