"""remove pfp from lost & found tables

Revision ID: 2eb73e0762dd
Revises: 89d29ca4c2a8
Create Date: 2025-12-05 11:23:42.640671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2eb73e0762dd'
down_revision: Union[str, Sequence[str], None] = '89d29ca4c2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('found_items', 'reporter_picture')
    op.drop_column('lost_items', 'reporter_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_items', sa.Column('reporter_picture', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('found_items', sa.Column('reporter_picture', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
