"""add image url to both items tables

Revision ID: 47ad9c6c4a77
Revises: 8972a1c95bd8
Create Date: 2025-12-07 11:42:47.879257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47ad9c6c4a77'
down_revision: Union[str, Sequence[str], None] = '8972a1c95bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "found_items",
        sa.Column("image", sa.String(), nullable=False, server_default="")
    )

    op.add_column(
        "lost_items",
        sa.Column("image", sa.String(), nullable=False, server_default="")
    )

    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('lost_items', 'image')
    op.drop_column('found_items', 'image')
    # ### end Alembic commands ###
