"""add cascade deletes to report & resolution

Revision ID: 5dc15cca803e
Revises: f06a44c13ca0
Create Date: 2026-01-04 12:00:59.791648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5dc15cca803e'
down_revision: Union[str, Sequence[str], None] = 'f06a44c13ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reports_item_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('resolutions_found_item_id_fkey'), 'resolutions', type_='foreignkey')
    op.create_foreign_key(None, 'resolutions', 'items', ['found_item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resolutions', type_='foreignkey')
    op.create_foreign_key(op.f('resolutions_found_item_id_fkey'), 'resolutions', 'items', ['found_item_id'], ['id'])
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_item_id_fkey'), 'reports', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
