"""update resolution with claimant id

Revision ID: 63c3a88ab6f5
Revises: f1e50c4d452b
Create Date: 2025-12-20 19:03:30.633265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63c3a88ab6f5'
down_revision: Union[str, Sequence[str], None] = 'f1e50c4d452b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resolutions', sa.Column('claimant_id', sa.Integer(), nullable=False))
    op.alter_column('resolutions', 'lost_item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_resolutions_claimant_id'), 'resolutions', ['claimant_id'], unique=False)
    op.create_foreign_key(None, 'resolutions', 'users', ['claimant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resolutions', type_='foreignkey')
    op.drop_index(op.f('ix_resolutions_claimant_id'), table_name='resolutions')
    op.alter_column('resolutions', 'lost_item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('resolutions', 'claimant_id')
    # ### end Alembic commands ###
