"""add resolution_id to notifications

Revision ID: 8f2a7abd8518
Revises: e372cdd06fd8
Create Date: 2025-12-22 14:36:23.174649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f2a7abd8518'
down_revision: Union[str, Sequence[str], None] = 'e372cdd06fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('resolution_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_notifications_resolution_id'), 'notifications', ['resolution_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'resolutions', ['resolution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_resolution_id'), table_name='notifications')
    op.drop_column('notifications', 'resolution_id')
    # ### end Alembic commands ###
