"""remove report name from Item

Revision ID: 9db3aead1f23
Revises: 2bea6051ce95
Create Date: 2025-12-16 19:01:00.622892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9db3aead1f23'
down_revision: Union[str, Sequence[str], None] = '2bea6051ce95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'reporter_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('reporter_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
