"""refactor gender in users to hostel

Revision ID: aa0f06a0b8f4
Revises: 2060a4435c91
Create Date: 2025-12-08 12:00:50.205209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa0f06a0b8f4'
down_revision: Union[str, Sequence[str], None] = '2060a4435c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hostel', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'hostel')
    # ### end Alembic commands ###
