"""remove lost_item_id field from resolutions

Revision ID: e372cdd06fd8
Revises: 63c3a88ab6f5
Create Date: 2025-12-22 12:15:27.214490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e372cdd06fd8'
down_revision: Union[str, Sequence[str], None] = '63c3a88ab6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolutions_lost_item_id'), table_name='resolutions')
    op.drop_constraint(op.f('resolutions_lost_item_id_fkey'), 'resolutions', type_='foreignkey')
    op.drop_column('resolutions', 'lost_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resolutions', sa.Column('lost_item_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('resolutions_lost_item_id_fkey'), 'resolutions', 'items', ['lost_item_id'], ['id'])
    op.create_index(op.f('ix_resolutions_lost_item_id'), 'resolutions', ['lost_item_id'], unique=False)
    # ### end Alembic commands ###
